#!name = 💯DNS映射
#!desc = 1.特定域名使用指定DNS进行解析 2.特殊地址使用规范DNS进行解析
#!icon = https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Server.png
#!author = B3TT3R
#!homepage = https://github.com/VirgilClyne/GetSomeFries/wiki/🌐-DNS
#!update = 2025-03-20

[Host]
# --- CUSTOM DNS ---
# > Encrypted DNS
dns.google = 8.8.8.8
dns64.dns.google = 2001:4860:4860::6464
cloudflare-dns.com = 104.16.249.249
1dot1dot1dot1.cloudflare-dns.com = 1.1.1.1
one.one.one.one = 1.0.0.1
dns.alidns.com = 223.5.5.5
doh.pub = 1.12.12.12
dot.pub = 120.53.53.53
doh.360.cn = 23.6.48.18
dot.360.cn = 101.198.198.198
dns.twnic.tw = 101.102.103.104
ordns.he.net = 74.82.42.42

# Synology Router
*.router.synology.com = server:system
# Asus Router
*.router.asus.com = server:system
# 小米 Mi WiFi Router
*.www.miwifi.com = server:system
*.miwifi.com = server:system

# GitHub
*.atom.io = server:https://101.102.103.104/dns-query
*.dependabot.com = server:https://101.102.103.104/dns-query
*.ghcr.io = server:https://101.102.103.104/dns-query
*.git.io = server:https://101.102.103.104/dns-query
*.github.blog = server:https://101.102.103.104/dns-query
*.github.com = server:https://101.102.103.104/dns-query
*.github.community = server:https://101.102.103.104/dns-query
*.github.dev = server:https://101.102.103.104/dns-query
*.github.io = server:https://101.102.103.104/dns-query
*.githubapp.com = server:https://101.102.103.104/dns-query
*.githubassets.com = server:https://101.102.103.104/dns-query
*.githubcopilot.com = server:https://101.102.103.104/dns-query
*.githubhackathon.com = server:https://101.102.103.104/dns-query
*.githubnext.com = server:https://101.102.103.104/dns-query
*.githubpreview.dev = server:https://101.102.103.104/dns-query
*.githubstatus.com = server:https://101.102.103.104/dns-query
*.githubuniverse.com = server:https://101.102.103.104/dns-query
*.githubusercontent.com = server:https://101.102.103.104/dns-query
*.myoctocat.com = server:https://101.102.103.104/dns-query
*.opensource.guide = server:https://101.102.103.104/dns-query
*.repo.new = server:https://101.102.103.104/dns-query
*.thegithubshop.com = server:https://101.102.103.104/dns-query
# GitHub Actions Artifacts
*.blob.core.windows.net = server:https://101.102.103.104/dns-query
*.github-cloud.s3.amazonaws.com = server:https://101.102.103.104/dns-query
# npmjs
*.npm.community = server:https://1.12.12.12/dns-query
*.npmjs.com = server:https://1.12.12.12/dns-query
*.npmjs.org = server:https://1.12.12.12/dns-query

# > Apple
# refer: https://support.apple.com/zh-cn/HT210060
*.networking.apple = server:https://doh.dns.apple.com/dns-query
*.www-cdn.icloud.com.akadns.net = server:https://doh.dns.apple.com/dns-query
# Apple.com
*.apple.com = server:119.29.29.29
# iCloud.com
*.icloud.com = server:https://doh.dns.apple.com/dns-query
*.apple-icloud.cn = server:https://1.12.12.12/dns-query
*.appleicloud.cn = server:https://1.12.12.12/dns-query
*.icloud-apple.cn = server:https://1.12.12.12/dns-query
*.icloud.com.cn = server:https://1.12.12.12/dns-query
*.icloud.net.cn = server:https://1.12.12.12/dns-query
*.icloudapple.cn = server:https://1.12.12.12/dns-query
*.me.com = server:https://1.12.12.12/dns-query
# Apple-CN
*.netcts.cdn-apple.com = server:https://doh.pub/dns-query
*.apple-mapkit.com = server:119.29.29.29

# Google CDN
*.blog.google = server:https://101.102.103.104/dns-query
*.googletraveladservices.com = server:https://101.102.103.104/dns-query
*.dl.google.com = server:https://101.102.103.104/dns-query
*.dl.l.google.com = server:https://101.102.103.104/dns-query
*.clientservices.googleapis.com = server:https://101.102.103.104/dns-query
*.update.googleapis.com = server:https://101.102.103.104/dns-query
*.translate.googleapis.com = server:https://101.102.103.104/dns-query
*.fonts.googleapis.com = server:https://101.102.103.104/dns-query
*.fonts.gstatic.com = server:https://101.102.103.104/dns-query

# Google STUN
*.stun.l.google.com = server:https://doh.pub/dns-query
*.stun?.l.google.com = server:https://doh.pub/dns-query

# > Alphabet
# refer: https://developers.google.com/speed/public-dns/docs/doh?hl=zh-cn
*.google = server:https://101.102.103.104/dns-query
*.google.com = server:https://101.102.103.104/dns-query
*.google.com.?? = server:https://101.102.103.104/dns-query
# Google sites
*.goog = server:https://101.102.103.104/dns-query
# Google 静态资源
*.gstatic.com = server:https://101.102.103.104/dns-query
# Google Photos
*.ggpht.com = server:https://101.102.103.104/dns-query
# Google 用户上传数据
*.googleusercontent.com = server:https://101.102.103.104/dns-query
# Google APIs
*.googleapis.com = server:https://101.102.103.104/dns-query
# Google backbone
*.1e100.net = server:https://101.102.103.104/dns-query
# Youtube sites
*.youtube = server:https://101.102.103.104/dns-query
# Youtube
*.youtube.com = server:https://101.102.103.104/dns-query
# Youtube 图片
*.ytimg.com = server:https://101.102.103.104/dns-query
# Youtube Video
*.googlevideo.com = server:https://101.102.103.104/dns-query
# Google Video Thumbnails
*.gvt?.com = server:https://101.102.103.104/dns-query
# reCaptcha
*.recaptcha.net = server:https://101.102.103.104/dns-query
# Gmail
*.gmail.com = server:https://101.102.103.104/dns-query
# Google Source
*.googlesource.com = server:https://101.102.103.104/dns-query
# Google AD Services
*.googleadservices.com = server:https://dns.adguard-dns.com/dns-query
# DoubleClick
*.doubleclick.net = server:https://101.102.103.104/dns-query
# AdSense
*.adsense.com = server:https://1.1.1.1/dns-query
# AdSense Custom Search Ads
*.adsensecustomsearchads.com = server:https://1.1.1.1/dns-query
# AdSense for mobile apps
*.adsenseformobileapps.com = server:https://1.1.1.1/dns-query
# Google shortened URLs
*.gle = server:https://101.102.103.104/dns-query
# Google URL Shortener
*.goo.gl = server:https://101.102.103.104/dns-query

# Twitter / X
twitter.com = server:https://101.102.103.104/dns-query
t.co = server:https://101.102.103.104/dns-query
*.twimg.com = server:https://101.102.103.104/dns-query
*.x.com = server:https://101.102.103.104/dns-query
*.pscp.tv = server:https://101.102.103.104/dns-query

# Telegram
*.graph.org = server:https://101.102.103.104/dns-query
*.t.me = server:https://101.102.103.104/dns-query
*.telegram.me = server:https://101.102.103.104/dns-query
*.telegram.org = server:https://101.102.103.104/dns-query
*.tg.dev = server:https://101.102.103.104/dns-query
*.tx.me = server:https://101.102.103.104/dns-query

# > Cloudflare
# refer: https://developers.cloudflare.com/1.1.1.1/encryption/dns-over-https/make-api-requests/
*.cloudflare.com = server:1.1.1.2
# Cloudflare Stream
*.cloudflarestream.com = server:1.1.1.2
# Cloudflare Client
*.cloudflareclient.com = server:1.1.1.2
# Cloudflare Web Analytics
*.cloudflareinsights.com = server:https://1.1.1.1/dns-query
# Cloudflare
*.every1dns.net = server:https://1.1.1.1/dns-query
# Cloudflare SSL Certificate
# *.cloudflaressl.com = server:https://1.1.1.1/dns-query
# Cloudflare DNS
*.cloudflare-dns.com = server:https://1.1.1.1/dns-query
# CloudFlare Workers
*.workers.dev = server:https://1.1.1.1/dns-query

# > 阿里巴巴
# refer: https://www.alidns.com
*.alibaba.cn = server:https://dns.alidns.com/dns-query
*.alibaba.com.cn = server:https://dns.alidns.com/dns-query
# Alibaba 中国
*.china.alibaba.com = server:https://dns.alidns.com/dns-query
# 1688
*.1688.com = server:https://dns.alidns.com/dns-query
# 淘宝
*.taobao.com = server:https://dns.alidns.com/dns-query
# 淘宝 缓存
*.tbcache.com = server:https://dns.alidns.com/dns-query
# 天猫
*.tmall.com = server:https://dns.alidns.com/dns-query
# 阿里 CDN
*.alicdn.com = server:https://dns.alidns.com/dns-query
# 阿里昆仑
*.alikunlun.com = server:https://dns.alidns.com/dns-query
# 云引擎应用平台
*.aliapp.com = server:https://dns.alidns.com/dns-query
# 上云平台
*.aliapp.org = server:https://dns.alidns.com/dns-query
# 阿里用户上传资料
*.alibabausercontent.com = server:https://dns.alidns.com/dns-query
# mmstat 数据统计 广告追踪
*.mmstat.com = server:https://dns.alidns.com/dns-query
# 淘宝短网址
*.tb.cn = server:https://dns.alidns.com/dns-query

# > 阿里云
# refer: https://www.alidns.com
# 阿里云
*.aliyun.* = server:https://dns.alidns.com/dns-query
# 阿里云 CDN
*.aliyuncdn.* = server:https://dns.alidns.com/dns-query
# 阿里云 API 服务
*.aliyuncs.com = server:https://dns.alidns.com/dns-query
# 阿里云 DDoS防护
*.aliyunddos????.com = server:https://dns.alidns.com/dns-query
# 阿里云盘
*.aliyundrive.com = server:https://dns.alidns.com/dns-query
# 阿里云盾
*.aliyundun.com = server:https://dns.alidns.com/dns-query
# 阿里云盾 Web 应用防火墙
*.aliyundunwaf.com = server:https://dns.alidns.com/dns-query
# 阿里云 内部
*.aliyun-inc.com = server:https://dns.alidns.com/dns-query

# > 蚂蚁集团
# refer: https://www.alidns.com
*.antgroup.com = server:https://dns.alidns.com/dns-query
# 蚂蚁金服
*.antfin.com = server:https://dns.alidns.com/dns-query
*.antfinancial.com = server:https://dns.alidns.com/dns-query
# 支付宝
*.alipay.com = server:https://dns.alidns.com/dns-query
*.alipay.com.cn = server:https://dns.alidns.com/dns-query
# 支付宝 HTTP DNS
*.alipaydns.com = server:https://dns.alidns.com/dns-query
# 支付宝 商家资源
*.alipayeshop.com = server:https://dns.alidns.com/dns-query
# 支付宝 Mdap
*.alipaylog.com = server:https://dns.alidns.com/dns-query
# 支付宝 静态资源
*.alipayobjects.com = server:https://dns.alidns.com/dns-query
# 支付宝 开放技术生态体系
*.alipay-eco.com = server:https://dns.alidns.com/dns-query

# > 腾讯
# refer: https://www.dnspod.cn/products/publicdns
*.tencent.com = server:https://doh.pub/dns-query
# 腾讯云
*.qcloud.com = server:https://doh.pub/dns-query
# 腾讯云CDN
*.qcloudcdn.cn = server:https://doh.pub/dns-query
*.qcloudcdn.com = server:https://doh.pub/dns-query
# 腾讯云对象储存
*.qcloudcos.com = server:https://doh.pub/dns-query
# 腾讯云静态资源
*.qcloudimg.com = server:https://doh.pub/dns-query
# 腾讯云超级管家
*.qcloudcjgj.com = server:https://doh.pub/dns-query
# 腾讯云网站管家
*.qcloudwzgj.com = server:https://doh.pub/dns-query
# 腾讯云主页管家
*.qcloudzygj.com = server:https://doh.pub/dns-query
# 腾讯开放云
*.myqcloud.com = server:https://doh.pub/dns-query
# 腾讯云
*.tencent-cloud.net = server:https://doh.pub/dns-query
# 腾讯云aiot解决方案
*.tencentcloud-aiot.com = server:https://doh.pub/dns-query
# 腾讯云API
*.tencentcloudapi.com = server:https://doh.pub/dns-query
# 腾讯云容器镜像服务TCR
*.tencentcloudcr.com = server:https://doh.pub/dns-query
# 腾讯云云市场
*.tencentcloudmarket.com = server:https://doh.pub/dns-query
# QQ
*.qq.com = server:https://doh.pub/dns-query
# 腾讯头像
*.qlogo.cn = server:https://doh.pub/dns-query
# 腾讯图片
*.qpic.cn = server:https://doh.pub/dns-query
# 微信
*.weixin.qq.com = server:https://doh.pub/dns-query
*.wx.qq.com = server:https://doh.pub/dns-query
*.weixin.com = server:https://doh.pub/dns-query
# 微信公众平台
*.weixinbridge.com = server:https://doh.pub/dns-query
# WeChat
*.wechat.com = server:https://doh.pub/dns-query
# 微信小程序
*.servicewechat.com = server:https://doh.pub/dns-query
# 微云
*.weiyun.com = server:https://doh.pub/dns-query
# 腾讯 图片 静态资源
*.gtimg.cn = server:https://doh.pub/dns-query
*.idqqimg.com = server:https://doh.pub/dns-query
# 腾讯 静态资源 CDN
*.cdn-go.cn = server:https://doh.pub/dns-query
# 腾讯云 智能云解析DNS
*.smtcdns.com = server:https://doh.pub/dns-query
*.smtcdns.net = server:https://doh.pub/dns-query
# 腾讯短网址
*.url.cn = server:https://doh.pub/dns-query

# > 百度
# refer: https://dudns.baidu.com/support/localdns/Address/index.html
*.baidu = server:180.76.76.76
*.baidu.com = server:180.76.76.76
# 百度 静态资源
*.bdimg.com = server:180.76.76.76
*.bdstatic.com = server:180.76.76.76
# 百度网盘
*.baidupcs.* = server:180.76.76.76
# 百度云CDN
*.baiduyuncdn.* = server:180.76.76.76
# 百度云DNS
*.baiduyundns.* = server:180.76.76.76
# 百度云 DNS
*.bdydns.* = server:180.76.76.76
# 百度云 CDN
*.bdycdn.* = server:180.76.76.76
# 百度云 域名
*.bdysite.com = server:180.76.76.76
*.bdysites.com = server:180.76.76.76
# 百度智能云
*.baidubce.* = server:180.76.76.76
# 百度智能云 DNS
*.bcedns.* = server:180.76.76.76
# 百度智能云 对象存储BOS
*.bcebos.com = server:180.76.76.76
# 百度智能云 播放器服务
*.bcevod.com = server:180.76.76.76
# 百度智能云 图片服务
*.bceimg.com = server:180.76.76.76
# 百度智能云 主机
*.bcehost.com = server:180.76.76.76
*.bcehosts.com = server:180.76.76.76
# 百度短网址
*.dwz.cn = server:180.76.76.76

# > Bytedance
# refer: https://www.volcengine.com/docs/6758/179060
# 艾特迷
*.amemv.com = server:180.184.1.1
# 西瓜 图片服务
*.bdxiguaimg.com = server:180.184.1.1
# 西瓜 静态资源
*.bdxiguastatic.com = server:180.184.1.1
# 字节跳动 UNPKG
*.byted-static.com = server:180.184.1.1
# 字节跳动
*.bytedance.* = server:180.184.1.1
# 字节跳动 DNS
*.bytedns.net = server:180.184.1.1
# 字节跳动 CDN 文件存储
*.bytednsdoc.com = server:180.184.1.1
# 字节跳动 Goofy
*.bytegoofy.com = server:180.184.1.1
# 字节跳动 图片服务
*.byteimg.com = server:180.184.1.1
# 字节跳动 SCM
*.bytescm.com = server:180.184.1.1
# 字节跳动 TOS
*.bytetos.com = server:180.184.1.1
# 飞书企业服务平台
*.bytexservice.com = server:180.184.1.1
# 抖音
*.douyin.com = server:180.184.1.1
# 抖音 静态资源
*.douyinpic.com = server:180.184.1.1
# 抖音 静态资源
*.douyinstatic.com = server:180.184.1.1
# 抖音 静态资源
*.douyinvod.com = server:180.184.1.1
# FeelGood平台
*.feelgood.cn = server:180.184.1.1
# 飞聊官网
*.feiliao.com = server:180.184.1.1
# 快手
*.gifshow.com = server:180.184.1.1
# 火山网
*.huoshan.com = server:180.184.1.1
# 火山直播
*.huoshanzhibo.com = server:180.184.1.1
# 抖音 dapm
*.ibytedapm.com = server:180.184.1.1
# 抖音 CDN
*.iesdouyin.com = server:180.184.1.1
# 西瓜视频
*.ixigua.com = server:180.184.1.1
# 快手
*.kspkg.com = server:180.184.1.1
# 抖音 静态资源
*.pstatp.com = server:180.184.1.1
# 今日头条
*.snssdk.com = server:180.184.1.1
# 今日头条
*.toutiao.com = server:180.184.1.1
# 今日头条
*.toutiao13.com = server:180.184.1.1
# 今日头条 静态资源
*.toutiao???.??? = server:180.184.1.1
# 头条云
*.toutiaocloud.cn = server:180.184.1.1
# 头条云
*.toutiaocloud.com = server:180.184.1.1
# 今日头条 建站
*.toutiaopage.com = server:180.184.1.1
# 悟空
*.wukong.com = server:180.184.1.1
# 字节跳动 API
*.zijieapi.com = server:180.184.1.1
# 字节跳动 图片服务
*.zijieimg.com = server:180.184.1.1
# 今日头条 网页版
*.zjbyte.com = server:180.184.1.1
# 字节跳动 CDN
*.zjcdn.com = server:180.184.1.1

# > BiliBili
*.bilibili.com = server:https://223.5.5.5/dns-query
# BiliBili API
*.biliapi.com = server:https://223.5.5.5/dns-query
*.biliapi.net = server:https://223.5.5.5/dns-query
# BiliBili CDN
*.bilicdn?.com = server:https://223.5.5.5/dns-query
# BiliBili 静态资源
*.hdslb.com = server:https://223.5.5.5/dns-query
*.hdslb.net = server:https://223.5.5.5/dns-query
# BiliBili 视频
*.bilivideo.com = server:https://223.5.5.5/dns-query
*.bilivideo.cn = server:https://223.5.5.5/dns-query
# BiliBili短网址
*.acg.tv = server:https://223.5.5.5/dns-query

# > 京东
*.jd.com = server:https://doh.pub/dns-query
# 京东 静态资源
*.360buyimg.com = server:https://doh.pub/dns-query
# 京东云
*.jdcloud.com = server:https://doh.pub/dns-query
# 京东云 缓存和存储
*.jcloudstatic.com = server:https://doh.pub/dns-query
# 京东云 静态资源
*.jcloudstatic.net = server:https://doh.pub/dns-query
# 京东云 全局负载均衡
*.jdgslb.com = server:https://doh.pub/dns-query
# 京东短网址
*.3.cn = server:https://doh.pub/dns-query

# > 🇨🇳 CHN
# CNNIC SDNS
# 中国政府网
*.gov.cn = server:1.2.4.8
*.政务 = server:1.2.4.8

# > Router/system DNS
*.lan = server:system
*.home.arpa = server:system
*.ts.net = server:system
*.instant.arubanetworks.com = server:system
*.setmeup.arubanetworks.com = server:system
*.router.asus.com = server:system
*.repeater.asus.com = server:system
*.asusrouter.com = server:system
*.routerlogin.net = server:system
*.tendawifi.com = server:system
*.tplinkwifi.net = server:system
*.tplogin.cn = server:system
*.tplinkap.net = server:system
*.tplinkeap.net = server:system
*.tplinkmodem.net = server:system
*.tplinkplclogin.net = server:system
*.tplinkrepeater.net = server:system
*.miwifi.com = server:system
*.zte.home = server:system
*.ui.direct = server:system
*.hiwifi.com = server:system
*.huaweimobilewifi.com = server:system
*.my.router = server:system
*.phicomm.me = server:system
*.router.ctc = server:system
*.peiluyou.com = server:system
*.airbox.home = server:system
*.homerouter.cpe = server:system
*.ntt.setup = server:system
*.pi.hole = server:system
*.plex.direct = server:system
*.app.plex.tv = server:system
*.routerlogin.com = server:system
*.samsung.router = server:system
*.web.setup = server:system
*.web.setup.home = server:system
*.in-addr.arpa = server:system
